// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fstfqbjppzzlyxcjsieb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdGZxYmpwcHp6bHl4Y2pzaWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTQ1NTIsImV4cCI6MjA3NDczMDU1Mn0.awbeXTAlR79B_1PcgeInCeMhvNnRQ1_9e8eB-tMLSMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});